name: PHP CI/CD

on:
  push:
    branches:
      - main

jobs:
  php-check-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: PHP Syntax Check
        shell: powershell
        run: |
          Get-ChildItem -Recurse -Filter *.php | ForEach-Object {
            php -l $_.FullName
          }

      - name: Deploy to Apache
        shell: powershell
        run: |
          Copy-Item `
            -Path "$env:GITHUB_WORKSPACE\*" `
            -Destination "C:\Apache24\htdocs\realtermproject" `
            -Recurse `
            -Force
