name: PHP CI/CD

on:
  push:
    branches:
      - main

jobs:
  php-check-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: PHP Syntax Check
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force

          Get-ChildItem -Recurse -Filter *.php | ForEach-Object {
              & "C:\php8\php.exe" -l $_.FullName
          }

      - name: Deploy to Apache
        shell: powershell
        run: |
          Copy-Item `
            -Path "$env:GITHUB_WORKSPACE\*" `
            -Destination "C:\Apache24\htdocs\realtermproject" `
            -Recurse `
            -Force
